---
title: "05 Exploring Assumptions"
author: "Peter Baumgartner"
date: "`r Sys.Date()`"
output: 
  html_notebook: 
   # next three lines define start of chapter numbers
    pandoc_args: [ 
      "--number-offset=5,0" 
    ]
    fig_caption: true
    number_sections: yes
    toc: yes
    toc_depth: 3
---
```{r label = "global-options", echo=FALSE, highlight=TRUE}
knitr::opts_chunk$set(
        message = F,
        error = F,
        warning = F,
        comment = NA,
        highlight = T,
        prompt = T
        )

### install and load some important packages
### https://github.com/tidyverse/tidyverse
if (!require("tidyverse")) {
        install.packages("tidyverse", repos = "http://cran.wu.ac.at/")
        library(tidyverse)
        }

### above command installed and loaded the core tidyverse packages:
# ggplot2, for data visualisation.
# dplyr, for data manipulation.
# tidyr, for data tidying.
# readr, for data import.
# purrr, for functional programming.
# tibble, for tibbles, a modern re-imagining of data frames

### above command installed but did not load yet the following packages:

### Working with specific types of vectors:
# hms, for times.
# stringr, for strings.
# lubridate, for date/times.
# forcats, for factors.

### Importing other types of data:
# feather, for sharing with Python and other languages.
# haven, for SPSS, SAS and Stata files.
# httr, for web apis.
# jsonlite for JSON.
# readxl, for .xls and .xlsx files.
# rvest, for web scraping.
# xml2, for XML.

### Modelling
# modelr, for modelling within a pipeline
# broom, for turning models into tidy data
```

## Install and load required packages



```{r install-packages}
if (!require("car")) {
        install.packages("car", repos = "http://cran.wu.ac.at/")
        library(car)
        }
if (!require("pastecs")) {
        install.packages("pastecs", repos = "http://cran.wu.ac.at/")
        library(pastecs)
        }
if (!require("psych")) {
        install.packages("psych", repos = "http://cran.wu.ac.at/")
        library(psych)
        }
```

## Load data set into memory

```{r load-data}
dlf <- read_delim("Data files/DownloadFestival.dat", delim = "\t", col_names = TRUE)
dlf1 <- read.delim("Data files/DownloadFestival.dat", header = TRUE)
```

